# Generated by Django 5.0.7 on 2024-08-03 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[("ACCEPTED", "Accepted"), ("REJECTED", "Rejected")],
                default="ACCEPTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["user", "uploaded_at"], name="api_image_user_id_bd1529_idx"
            ),
        ),
    ]
