# Generated by Django 5.0.7 on 2024-08-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_image_status_alter_image_image_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="image",
            name="api_image_user_id_bd1529_idx",
        ),
        migrations.RemoveField(
            model_name="caption",
            name="generated_at",
        ),
        migrations.RemoveField(
            model_name="image",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="image",
            name="labels",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="caption",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.image"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="nsfw_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="image",
            name="status",
            field=models.CharField(default="PENDING", max_length=10),
        ),
    ]
